services:
  nginx:
    container_name: daodin_nginx
    image: jonasal/nginx-certbot:latest
    restart: always
    environment:
      CERTBOT_EMAIL: $CERTBOT_EMAIL
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - daodin

  app:
    container_name: daodin_node
    image: node:20-alpine
    command: sh -c "cd /app/Backend && npm install && node index.js"
    init: true
    restart: always
    volumes:
      - ./Backend:/app/Backend
      - picture_storage:/app/static
      - node_modules:/app/Backend/node_modules
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - daodin
    depends_on:
      - nginx

  python:
    container_name: daodin_python
    image: python:3.11
    command: sh -c "cd /app/NLP_Model && pip install --upgrade pip && pip install -r requirements.txt && python api.py"
    init: true
    restart: always
    volumes:
      - ./NLP_Model:/app/NLP_Model
      - python-packages:/lib/python3.11/site-packages
    networks:
      - daodin
    ports:
      - "5000:5000"
    expose:
      - "5000"

volumes:
  node_modules:
  picture_storage:
  nginx_secrets:
  python-packages:


networks:
  daodin:
    driver: bridge
